# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('task_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('close_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
