# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='flag',
            field=models.CharField(default=datetime.datetime(2017, 12, 1, 6, 48, 31, 244672, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
